version: '3.8'
services:
  app:
    build: .
    image: inventario-lia-app:latest
    container_name: laravel_prod
    ports:
      - "8080:80" # Accederás por el puerto 8080
    restart: always
    volumes:
      # IMPORTANTE: Mapeamos solo la base de datos para no perder datos al reiniciar
      - ./database/database.sqlite:/var/www/html/database/database.sqlite